-- ============================================================
-- 003_seed_demo_products.sql
-- Produtos de demonstracao para storefront ficar com conteudo
-- 10 produtos platform_owned (sem seller, 100% lucro plataforma)
-- ============================================================

INSERT INTO products (
    id, seller_id, category_id, kind, status, slug, title, subtitle, description,
    short_description, price_cents, currency, license_kind, tech_stack,
    requirements, install_instructions, api_keys_required, estimated_install_min,
    cover_image_url, is_platform_owned, platform_resale_enabled,
    qa_verdict, qa_confidence_score, qa_last_check_at, approved_at, published_at,
    sales_count, view_count, avg_rating, review_count
) VALUES

-- 1. Agente WhatsApp
(gen_random_uuid(), NULL,
 (SELECT id FROM categories WHERE slug='agentes-ia'),
 'ai_agent', 'approved',
 'agente-whatsapp-rag-cas-001',
 'Agente WhatsApp com RAG e Memoria',
 'Atendente IA 24/7 com base de conhecimento personalizada',
 E'Agente completo de atendimento ao cliente via WhatsApp com:\n\n- RAG vetorial (pgvector + embeddings OpenAI)\n- Memoria de conversa persistente por usuario\n- Integracao Evolution API (WhatsApp Web)\n- Handoff humano automatico\n- Analytics de conversas\n- Suporte multi-instancia (varios numeros)\n\nIdeal para suporte tecnico, vendas e atendimento B2B/B2C.',
 'Atendente IA 24/7 com RAG, memoria persistente e integracao Evolution API.',
 14900, 'BRL', 'unlimited',
 ARRAY['Node.js','PostgreSQL','OpenAI','Evolution API','pgvector'],
 'Postgres 14+ com pgvector. Conta OpenAI com $20+ em credito. Evolution API rodando.',
 E'1. docker compose up -d\n2. npm install\n3. cp .env.example .env (preencher OPENAI_KEY e EVOLUTION_URL)\n4. node bin/migrate.js\n5. node bin/ingest-knowledge.js ./knowledge-base/\n6. pm2 start ecosystem.config.js',
 ARRAY['OPENAI_API_KEY','EVOLUTION_API_TOKEN'],
 25, 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800',
 TRUE, FALSE, 'approved', 0.94, NOW(), NOW(), NOW(),
 247, 1820, 4.8, 31),

-- 2. Workflow n8n CRM
(gen_random_uuid(), NULL,
 (SELECT id FROM categories WHERE slug='workflows-n8n'),
 'n8n_workflow', 'approved',
 'workflow-n8n-crm-vendas-cas-002',
 'CRM de Vendas n8n com Pipeline Visual',
 'Automacao completa de funil de vendas',
 E'Workflow n8n completo de CRM com:\n- 5 estagios de funil (Lead -> Qualificado -> Proposta -> Negociacao -> Ganho)\n- Captura leads (forms, webhooks, planilhas)\n- Lead scoring automatico\n- Email cadencias\n- Notificacoes Slack/Telegram\n- Dashboard Metabase\n- Webhook para CRMs externos',
 'Pipeline visual de vendas com lead scoring + cadencia de emails.',
 7900, 'BRL', 'single_use',
 ARRAY['n8n','PostgreSQL','SendGrid','Slack'],
 'n8n self-hosted ou cloud. Conta SendGrid free tier basta.',
 'Importe o JSON em Settings > Import Workflow no n8n. Configure credenciais.',
 ARRAY['SENDGRID_API_KEY','SLACK_WEBHOOK_URL'],
 10, 'https://images.unsplash.com/photo-1551434678-e076c223a692?w=800',
 TRUE, FALSE, 'approved', 0.91, NOW(), NOW(), NOW(),
 134, 980, 4.7, 18),

-- 3. Script Node Scraper
(gen_random_uuid(), NULL,
 (SELECT id FROM categories WHERE slug='scripts'),
 'node_script', 'approved',
 'scraper-ecommerce-puppeteer-cas-003',
 'Scraper E-commerce Universal (Puppeteer)',
 'Coleta produtos de qualquer loja online',
 E'Scraper Node.js com Puppeteer que extrai:\n- Catalogo completo (titulo, preco, descricao, imagens)\n- Variacoes de produto (tamanhos, cores)\n- Reviews e ratings\n- Disponibilidade em estoque\n- Multi-paginacao automatica\n- Anti-detection bypass (stealth plugin)\n- Export: JSON, CSV, Postgres, MongoDB\n\nTestado em: Mercado Livre, Amazon, Shopify, WooCommerce.',
 'Coleta catalogo completo de qualquer e-commerce com anti-detection.',
 4900, 'BRL', 'unlimited',
 ARRAY['Node.js','Puppeteer','Stealth Plugin'],
 'Node 18+. RAM 2GB+ por instancia.',
 'npm install && node scrape.js --url=https://loja.com --output=produtos.json',
 ARRAY[]::TEXT[],
 5, 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=800',
 TRUE, FALSE, 'approved', 0.88, NOW(), NOW(), NOW(),
 89, 2340, 4.5, 22),

-- 4. Agente RAG Documentos
(gen_random_uuid(), NULL,
 (SELECT id FROM categories WHERE slug='agentes-ia'),
 'ai_agent', 'approved',
 'agente-rag-documentos-cas-004',
 'Chatbot RAG para Documentos PDF/Word',
 'Pergunte qualquer coisa aos seus documentos',
 E'Sistema RAG completo para empresas:\n- Ingestao automatica de PDFs, DOCX, TXT, HTML\n- Chunking inteligente (semantic + overlap)\n- Embeddings OpenAI text-embedding-3\n- Busca vetorial pgvector\n- Reranking com Cohere\n- Streaming de respostas\n- Citacao de fontes com link direto\n- Interface web inclusa (Next.js)',
 'RAG para PDFs/DOCX/HTML com citacao de fontes e reranking.',
 19900, 'BRL', 'unlimited',
 ARRAY['Python','LangChain','pgvector','OpenAI','Cohere','Next.js'],
 'Postgres 14+ com pgvector. OpenAI key. Cohere trial OK.',
 'docker compose up + python ingest.py ./docs/ + npm run dev',
 ARRAY['OPENAI_API_KEY','COHERE_API_KEY'],
 30, 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800',
 TRUE, FALSE, 'approved', 0.96, NOW(), NOW(), NOW(),
 412, 3120, 4.9, 58),

-- 5. Automacao Email Marketing
(gen_random_uuid(), NULL,
 (SELECT id FROM categories WHERE slug='automacoes'),
 'automation', 'approved',
 'email-marketing-cadencia-cas-005',
 'Email Marketing com Cadencia Inteligente',
 'Sequencias de email + analytics + warm-up',
 E'Plataforma de email marketing completa:\n- Editor visual de templates (MJML)\n- Cadencias condicionais (se abriu -> email A, se nao -> email B)\n- Analytics em tempo real (open, click, conversion)\n- Warm-up automatico de IP/dominio\n- DKIM/SPF/DMARC checker\n- Lista validacao em bulk\n- Integracao com qualquer SMTP',
 'Cadencias condicionais + analytics + warm-up de IP.',
 9900, 'BRL', 'subscription_monthly',
 ARRAY['Node.js','PostgreSQL','Redis','MJML','SMTP'],
 'Servidor SMTP (Postmark/SES/Mailgun). Postgres + Redis.',
 'docker compose up -d && node bin/migrate.js && node bin/start.js',
 ARRAY['SMTP_HOST','SMTP_USER','SMTP_PASS'],
 20, 'https://images.unsplash.com/photo-1633409361618-c73427e4e206?w=800',
 TRUE, FALSE, 'approved', 0.89, NOW(), NOW(), NOW(),
 178, 1450, 4.6, 27),

-- 6. Script Python Trader
(gen_random_uuid(), NULL,
 (SELECT id FROM categories WHERE slug='scripts'),
 'python_script', 'approved',
 'trader-bot-binance-cas-006',
 'Bot Trader Binance com Backtesting',
 'Estrategia RSI+MACD com paper trading',
 E'Bot de trading completo para Binance:\n- Estrategias: RSI, MACD, Bollinger Bands, EMA crossover\n- Backtesting historico (anos de candles)\n- Paper trading (simulacao real)\n- Stop loss e take profit dinamicos\n- Webhook TradingView -> ordem\n- Telegram alerts\n- Dashboard web (Streamlit)',
 'RSI+MACD com backtesting e paper trading.',
 12900, 'BRL', 'unlimited',
 ARRAY['Python','ccxt','pandas','TA-Lib','Streamlit'],
 'Python 3.10+. Conta Binance com API key.',
 'pip install -r requirements.txt && python bot.py --strategy=rsi --paper',
 ARRAY['BINANCE_API_KEY','BINANCE_SECRET'],
 15, 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800',
 TRUE, FALSE, 'approved', 0.85, NOW(), NOW(), NOW(),
 67, 1890, 4.4, 19),

-- 7. Prompt Pack GPT-4 Vendas
(gen_random_uuid(), NULL,
 (SELECT id FROM categories WHERE slug='prompt-packs'),
 'prompt_pack', 'approved',
 'prompt-pack-vendas-b2b-cas-007',
 'Prompt Pack: 50 Prompts B2B Sales',
 'Templates testados para SDRs e closers',
 E'50 prompts otimizados para vendas B2B:\n- Pesquisa de prospect (LinkedIn, sites)\n- Cold email com personalization\n- Follow-up sequences\n- Objection handling\n- Proposal generation\n- Negociacao avancada\n- Discovery questions\n- Demo scripts\n\nFunciona com GPT-4, Claude, Gemini.',
 '50 prompts para SDRs e closers B2B com GPT-4/Claude.',
 1900, 'BRL', 'single_use',
 ARRAY['OpenAI','Anthropic','Gemini'],
 'Qualquer LLM com API.',
 'PDF inclui prompts prontos + Notion template.',
 ARRAY[]::TEXT[],
 2, 'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=800',
 TRUE, FALSE, 'approved', 0.82, NOW(), NOW(), NOW(),
 523, 4120, 4.7, 89),

-- 8. Template Dashboard Admin
(gen_random_uuid(), NULL,
 (SELECT id FROM categories WHERE slug='templates'),
 'template', 'approved',
 'template-dashboard-admin-next-cas-008',
 'Template Dashboard Admin Next.js 15',
 'Painel completo com auth, RBAC, CRUD',
 E'Template de painel admin pronto:\n- Next.js 15 + Tailwind 4 + shadcn/ui\n- Auth com JWT duplo (access+refresh)\n- RBAC (admin, staff, user)\n- CRUD generico com tabela paginada\n- Graficos Recharts\n- File upload S3/MinIO\n- Dark mode + i18n (pt-BR/EN)\n- Testes E2E Playwright',
 'Next 15 + Tailwind + shadcn + JWT + RBAC + Recharts.',
 24900, 'BRL', 'unlimited',
 ARRAY['Next.js 15','Tailwind 4','shadcn/ui','Prisma','Recharts'],
 'Node 20+. Postgres opcional.',
 'pnpm install && pnpm dev',
 ARRAY[]::TEXT[],
 10, 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800',
 TRUE, FALSE, 'approved', 0.93, NOW(), NOW(), NOW(),
 198, 2670, 4.8, 36),

-- 9. Agente Multi-CrewAI
(gen_random_uuid(), NULL,
 (SELECT id FROM categories WHERE slug='agentes-ia'),
 'ai_agent', 'approved',
 'crew-multi-agent-pesquisa-cas-009',
 'Multi-Agent CrewAI Pesquisa+Redacao',
 'Time de 4 agentes que pesquisa e escreve artigos',
 E'CrewAI com 4 agentes especializados:\n1. Researcher: busca web (SerpAPI, Tavily) e extrai dados\n2. Analyst: sintetiza informacoes\n3. Writer: redige artigo SEO-otimizado\n4. Editor: revisa e melhora\n\nEntrega artigo completo (1500+ palavras) em ~3 min com fontes citadas.',
 'Time CrewAI: pesquisa + analise + redacao + edicao SEO.',
 17900, 'BRL', 'unlimited',
 ARRAY['Python','CrewAI','OpenAI','SerpAPI','Tavily'],
 'Python 3.11+. Keys: OpenAI + SerpAPI ou Tavily.',
 'pip install crewai && python crew.py --tema="seu topico"',
 ARRAY['OPENAI_API_KEY','SERPAPI_KEY'],
 15, 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800',
 TRUE, FALSE, 'approved', 0.92, NOW(), NOW(), NOW(),
 145, 1670, 4.6, 24),

-- 10. Workflow n8n WhatsApp Broadcast
(gen_random_uuid(), NULL,
 (SELECT id FROM categories WHERE slug='workflows-n8n'),
 'n8n_workflow', 'approved',
 'whatsapp-broadcast-n8n-cas-010',
 'WhatsApp Broadcast n8n com Anti-Ban',
 'Disparo em massa controlado com Evolution',
 E'Workflow n8n de broadcast WhatsApp:\n- Disparo controlado (1 msg / 3-7s aleatorio)\n- Lista segmentada por tags\n- Mensagens personalizadas com variaveis\n- Detection de bloqueio + pausa automatica\n- Log de status (entregue, lido, falhou)\n- Suporte multi-instancia (rotaciona numeros)\n- Pausa automatica fim de semana',
 'Disparo controlado + anti-ban + multi-instancia.',
 8900, 'BRL', 'unlimited',
 ARRAY['n8n','Evolution API','PostgreSQL'],
 'n8n + Evolution API rodando. Postgres opcional.',
 'Importe JSON no n8n. Configure credenciais Evolution.',
 ARRAY['EVOLUTION_API_URL','EVOLUTION_API_TOKEN'],
 8, 'https://images.unsplash.com/photo-1611162616475-46b635cb6868?w=800',
 TRUE, FALSE, 'approved', 0.87, NOW(), NOW(), NOW(),
 234, 3450, 4.7, 41)

ON CONFLICT (slug) DO NOTHING;

-- Atualiza search_tsv para todos (trigger ja fez no INSERT, mas garante)
UPDATE products SET updated_at = NOW() WHERE id IN (
  SELECT id FROM products WHERE slug LIKE '%-cas-0%'
);
